### ISSUE TITLE
[Bug] TypeError: Cannot read properties of undefined (reading 'get')

### ISSUE THREAD

**Issue by bouncycatt** [storybookjs/addon-react-native-web#30] opened 2021-12-27 08:03 UTC
### Describe the bug
I installed addon-react-native-web, then added the addon to .storybook/main.ts and then I received this error. I wanted to use addon-react-native-web to run [expo-linear-gradient](https://docs.expo.dev/versions/latest/sdk/linear-gradient/) in Storybook. Storybook worked fine without expo-linear-gradient. At the same time react-native-web displays gradients without any errors. 

### Steps to reproduce the behavior
1. Installed addon-react-native-web
2. Added configuration to .storybook/main.ts
3. Run storybook

### Expected behavior
Storybook works and displays expo gradient. 

### Screenshots and/or logs
I receive this error: 
```
yarn run v1.22.17
$ PLATFORM=web start-storybook -p 6006
info @storybook/react v6.4.9
info 
info => Loading presets
info => Serving static files from /Users/user/dev/app/app/src/_ds/assets/fonts at /
info => Loading custom manager config
info => Using implicit CSS loaders
info => Loading custom manager config
info => Using default Webpack4 setup
(node:69327) DeprecationWarning: Default PostCSS plugins are deprecated. When switching to '@storybook/addon-postcss',
you will need to add your own plugins, such as 'postcss-flexbugs-fixes' and 'autoprefixer'.

See https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated-default-postcss-plugins for details.
(Use `node --trace-deprecation ...` to show where the warning was created)
0% compilingERR! TypeError: Cannot read properties of undefined (reading 'get')
ERR!     at /Users/user/dev/app/app/node_modules/webpack/lib/DefinePlugin.js:292:38
ERR!     at SyncHook.eval [as call] (eval at create (/Users/user/dev/app/app/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:13:1)
ERR!     at SyncHook.lazyCompileHook (/Users/user/dev/app/app/node_modules/tapable/lib/Hook.js:154:20)
ERR!     at Compiler.newCompilation (/Users/user/dev/app/app/node_modules/@storybook/builder-webpack4/node_modules/webpack/lib/Compiler.js:631:26)
ERR!     at /Users/user/dev/app/app/node_modules/@storybook/builder-webpack4/node_modules/webpack/lib/Compiler.js:667:29
ERR!     at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/user/dev/app/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
ERR!     at AsyncSeriesHook.lazyCompileHook (/Users/user/dev/app/app/node_modules/tapable/lib/Hook.js:154:20)
ERR!     at Compiler.compile (/Users/user/dev/os/app/node_modules/@storybook/builder-webpack4/node_modules/webpack/lib/Compiler.js:662:28)
ERR!     at /Users/user/dev/app/app/node_modules/@storybook/builder-webpack4/node_modules/webpack/lib/Watching.js:77:18
ERR!     at _next0 (eval at create (/Users/user/dev/app/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:25:1)
ERR!     at eval (eval at create (/Users/user/dev/app/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:34:1)
ERR!     at watchRunHook (/Users/user/dev/app/app/node_modules/webpack-virtual-modules/index.js:173:5)
ERR!     at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/user/dev/app/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:30:1)
ERR!     at AsyncSeriesHook.lazyCompileHook (/Users/user/dev/app/app/node_modules/tapable/lib/Hook.js:154:20)
ERR!     at Watching._go (/Users/user/dev/app/app/node_modules/@storybook/builder-webpack4/node_modules/webpack/lib/Watching.js:41:32)
ERR!     at /Users/user/dev/app/app/node_modules/@storybook/builder-webpack4/node_modules/webpack/lib/Watching.js:33:9
ERR!  TypeError: Cannot read properties of undefined (reading 'get')
ERR!     at /Users/user/dev/app/app/node_modules/webpack/lib/DefinePlugin.js:292:38
ERR!     at SyncHook.eval [as call] (eval at create (/Users/user/dev/app/app/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:13:1)
ERR!     at SyncHook.lazyCompileHook (/Users/user/dev/app/app/node_modules/tapable/lib/Hook.js:154:20)
ERR!     at Compiler.newCompilation (/Users/user/dev/app/app/node_modules/@storybook/builder-webpack4/node_modules/webpack/lib/Compiler.js:631:26)
ERR!     at /Users/user/dev/app/app/node_modules/@storybook/builder-webpack4/node_modules/webpack/lib/Compiler.js:667:29
ERR!     at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/user/dev/app/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
ERR!     at AsyncSeriesHook.lazyCompileHook (/Users/user/dev/app/app/node_modules/tapable/lib/Hook.js:154:20)
ERR!     at Compiler.compile (/Users/user/dev/app/app/node_modules/@storybook/builder-webpack4/node_modules/webpack/lib/Compiler.js:662:28)
ERR!     at /Users/user/dev/app/app/node_modules/@storybook/builder-webpack4/node_modules/webpack/lib/Watching.js:77:18
ERR!     at _next0 (eval at create (/Users/user/dev/app/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:25:1)
ERR!     at eval (eval at create (/Users/user/dev/app/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:34:1)
ERR!     at watchRunHook (/Users/user/dev/app/app/node_modules/webpack-virtual-modules/index.js:173:5)
ERR!     at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/user/dev/app/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:30:1)
ERR!     at AsyncSeriesHook.lazyCompileHook (/Users/user/dev/app/app/node_modules/tapable/lib/Hook.js:154:20)
ERR!     at Watching._go (/Users/user/dev/app/app/node_modules/@storybook/builder-webpack4/node_modules/webpack/lib/Watching.js:41:32)
ERR!     at /Users/user/dev/app/app/node_modules/@storybook/builder-webpack4/node_modules/webpack/lib/Watching.js:33:9

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.

error Command failed with exit code 1.
```

### Environment
 - OS: web
 - Node.js version: v16.13.1
 - NPM version: 8.1.2
 - Browser: chrome
 - Browser version: 96.0.4664.110 
 - expo-linear-gradient: ~10.0.3

### .storybook/main.ts
```
module.exports = {
  stories: ['../src/**/*.stories.@(ts|tsx)'],
  addons: [
    '@storybook/addon-links',
    '@storybook/addon-essentials',
    '@storybook/addon-a11y',
    {
      name: '@storybook/addon-react-native-web',
      options: {
        modulesToTranspile: ['expo-linear-gradient'],
      },
    },
  ],
  staticDirs: ['../src/_ds/assets/fonts'],
  framework: '@storybook/react',
}
```

### package.json
```
{
  "name": "app",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "react-native start",
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "web": "PLATFORM=web react-scripts-customizable start",
    "web:build": "PLATFORM=web react-scripts-customizable build",
    "test": "jest",
    "lint": "eslint . --ext .js,.jsx,.ts,.tsx",
    "prettier": "prettier --write .",
    "storybook": "PLATFORM=web start-storybook -p 6006",
    "build-storybook": "PLATFORM=web build-storybook"
  },
  "dependencies": {
    "expo": "^43.0.4",
    "expo-constants": "~12.1.3",
    "expo-linear-gradient": "~10.0.3",
    "react": "17.0.2",
    "react-dom": "^17.0.2",
    "react-native": "0.66.4",
    "react-native-web": "^0.17.5",
    "react-scripts-customizable": "^5.0.0"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/plugin-proposal-class-properties": "^7.16.5",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "@storybook/addon-a11y": "^6.4.9",
    "@storybook/addon-actions": "^6.4.9",
    "@storybook/addon-essentials": "^6.4.9",
    "@storybook/addon-links": "^6.4.9",
    "@storybook/addon-react-native-web": "^0.0.16",
    "@storybook/react": "^6.4.9",
    "@types/jest": "^26.0.23",
    "@types/react-dom": "^17.0.11",
    "@types/react-native": "^0.66.4",
    "@types/react-test-renderer": "^17.0.1",
    "@typescript-eslint/eslint-plugin": "^5.7.0",
    "babel-jest": "^26.6.3",
    "babel-loader": "^8.2.3",
    "babel-plugin-module-resolver": "^4.1.0",
    "babel-plugin-react-native-web": "^0.17.5",
    "babel-preset-expo": "^8.5.1",
    "chromatic": "^6.2.3",
    "eslint": "^7.14.0",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "^0.66.2",
    "react-test-renderer": "17.0.2",
    "typescript": "^4.5.4"
  },
  "resolutions": {
    "@types/react": "^17"
  },
  "jest": {
    "preset": "react-native-web",
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js",
      "jsx",
      "json",
      "node"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}
```

### babel.config.js
```
const isWeb = process.env.PLATFORM === 'web'

module.exports = api => {
  api.cache(true)

  const presets = isWeb
    ? [
        /**
         * Compilation for web platform. Removes unused
         * libraries (which we use in native platforms).
         */
        'babel-preset-expo',
      ]
    : [
        // Compilation for native platforms.
        'module:metro-react-native-babel-preset',
      ]

  const plugins = isWeb
    ? [
        // Web bundle size optimization.
        'react-native-web',
      ]
    : []

  const alias = isWeb
    ? {
        '^react-native$': 'react-native-web',
      }
    : {}

  return {
    presets: [...presets],
    plugins: [
      ...plugins,
      [
        'module-resolver',
        {
          root: ['./src'],
          extensions: ['.ts', '.tsx'],
          alias: {
            ...alias,
            '@ds': './src/_ds',
          },
        },
      ],
    ],
  }
}
```

### Error before addon-react-native-web installation
After I installed expo-linear-gradient I received this error (before I installed addon-react-native-web): 
```
ERROR in ./node_modules/react-native/index.js 14:7
Module parse failed: Unexpected token (14:7)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| 
| // Components
> import typeof AccessibilityInfo from './Libraries/Components/AccessibilityInfo/AccessibilityInfo';
| import typeof ActivityIndicator from './Libraries/Components/ActivityIndicator/ActivityIndicator';
| import typeof Button from './Libraries/Components/Button';
 @ ./node_modules/expo-linear-gradient/build/LinearGradient.js 2:0-54 15:78-86 17:36-48
 @ ./src/_ds/components/general/compound/Header/Header.tsx
 @ ./src/_ds/components/general/compound/Header/Header.stories.tsx
 @ ./src sync ^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.stories\.(ts|tsx))$
 @ ./generated-stories-entry.js
 @ multi ./node_modules/@storybook/core-server/node_modules/@storybook/core-client/dist/esm/globals/polyfills.js ./node_modules/@storybook/core-server/node_modules/@storybook/core-client/dist/esm/globals/globals.js ./node_modules/webpack-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined ./storybook-init-framework-entry.js ./node_modules/@storybook/addon-docs/dist/esm/frameworks/common/config.js-generated-config-entry.js ./node_modules/@storybook/addon-docs/dist/esm/frameworks/react/config.js-generated-config-entry.js ./node_modules/@storybook/react/dist/esm/client/preview/config-generated-config-entry.js ./node_modules/@storybook/addon-links/dist/esm/preset/addDecorator.js-generated-config-entry.js ./node_modules/@storybook/addon-actions/dist/esm/preset/addDecorator.js-generated-config-entry.js ./node_modules/@storybook/addon-actions/dist/esm/preset/addArgs.js-generated-config-entry.js ./node_modules/@storybook/addon-backgrounds/dist/esm/preset/addDecorator.js-generated-config-entry.js ./node_modules/@storybook/addon-backgrounds/dist/esm/preset/addParameter.js-generated-config-entry.js ./node_modules/@storybook/addon-measure/dist/esm/preset/addDecorator.js-generated-config-entry.js ./node_modules/@storybook/addon-outline/dist/esm/preset/addDecorator.js-generated-config-entry.js ./.storybook/preview.ts-generated-config-entry.js ./generated-stories-entry.js

```

**Comment by dannyhw** [comment] 2021-12-27 20:11
Your Babel configuration is a bit non standard, I'm not sure why you need to separate the web config from the native config. It's hard to tell what the issue is without debugging. This seems like an issue with a webpack loader or some missing config just based on my first look at the logs.

Is the repo public? Or can you create a minimal reproduction of the problem in a public repo?

**Comment by bouncycatt** [comment] 2021-12-28 13:07
I found this issue with my error: https://stackoverflow.com/questions/67070802/webpack-5-and-storybook-6-integration-throws-an-error-in-defineplugin-js
But I don't use Webpack 5.  

And I found this tutorial https://gist.github.com/shilman/8856ea1786dcd247139b47b270912324#upgrade with this message:
`NOTE: Before you try out Storybook's webpack5 support, make sure your project works with Webpack 5. For example, create-react-app (CRA) is not webpack5-compatible, so if you have a CRA project, you'll need to wait until webpack5 support is released. Once you've verified webpack5 in your project, you can either do a clean install or an upgrade.`

And yes, I am using CRA. Maybe you have some ideas?

**Comment by bouncycatt** [comment] 2021-12-28 13:13
When I removed DefinePlugin, it works:
```
import webpack from 'webpack'
import path from 'path'

export type Options = {
  modulesToTranspile?: string[]
  babelPlugins?: string[]
  projectRoot?: string
}

export const getBabelPlugins = (options: Options) => {
  let reactNativeWeb = 'react-native-web'
  if (options.babelPlugins && Array.isArray(options.babelPlugins)) {
    return [reactNativeWeb, ...options.babelPlugins]
  }
  return [reactNativeWeb]
}

const getModule = (name: string) => path.join('node_modules', name)

// copied from https://github.com/expo/expo-cli/blob/master/packages/webpack-config/src/loaders/createBabelLoader.ts
const DEFAULT_INCLUDES = [
  getModule('react-native'),
  getModule('react-navigation'),
  getModule('expo'),
  getModule('unimodules'),
  getModule('@react'),
  getModule('@expo'),
  getModule('@use-expo'),
  getModule('@unimodules'),
  getModule('native-base'),
  getModule('styled-components'),
]

const DEFAULT_EXCLUDES = [
  '/node_modules',
  '/bower_components',
  '/.expo/',
  // Prevent transpiling webpack generated files.
  '(webpack)',
]

module.exports = {
  stories: ['../src/**/*.stories.@(ts|tsx)'],
  addons: [
    {
      name: '@storybook/addon-essentials',
      options: {
        backgrounds: false,
        outline: false,
      },
    },
    '@storybook/addon-links',
    '@storybook/addon-a11y',
    // {
    //   name: '@storybook/addon-react-native-web',
    //   options: {
    //     modulesToTranspile: ['expo-linear-gradient', 'expo-constants'],
    //   },
    // },
  ],
  webpackFinal: async (config: any, options: Options) => {
    // swap out react-native for react-native-web
    config.resolve.alias = {
      'react-native$': 'react-native-web',
    }

    // Add __DEV__ global variable which is relied on by many libraries
    // config.plugins.push(
    //   new webpack.DefinePlugin({
    //     'process.env.NODE_ENV': JSON.stringify(
    //       process.env.NODE_ENV || 'development',
    //     ),
    //     __DEV__: process.env.NODE_ENV !== 'production' || true,
    //   }),
    // )

    // plugin suggested in reanimated docs https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/web-support/
    // config.plugins.push(new webpack.DefinePlugin({ process: { env: {} } }))

    const babelPlugins = getBabelPlugins(options)
    const root = options.projectRoot ?? process.cwd()
    const userModules = options.modulesToTranspile?.map(getModule) ?? []
    const modules = [...DEFAULT_INCLUDES, ...userModules]

    // fix for uncompiled react-native dependencies
    config.module.rules.push({
      test: /\.(js|jsx|ts|tsx)$/,
      loader: 'babel-loader',
      // include logic copied from https://github.com/expo/expo-cli/blob/master/packages/webpack-config/src/loaders/createBabelLoader.ts
      include(filename: string) {
        if (!filename) {
          return false
        }

        for (const possibleModule of modules) {
          if (filename.includes(path.normalize(possibleModule))) {
            return true
          }
        }

        if (filename.includes(root)) {
          for (const excluded of DEFAULT_EXCLUDES) {
            if (filename.includes(path.normalize(excluded))) {
              return false
            }
          }
          return true
        }
        return false
      },
      options: {
        root,
        presets: [
          [
            'module:metro-react-native-babel-preset',
            {
              useTransformReactJSXExperimental: true,
            },
          ],
          [
            '@babel/preset-react',
            {
              runtime: 'automatic',
            },
          ],
        ],
        plugins: [...babelPlugins, '@babel/plugin-proposal-class-properties'],
      },
    })

    config.resolve.extensions = [
      '.web.js',
      '.web.jsx',
      '.web.ts',
      '.web.tsx',
      ...config.resolve.extensions,
    ]

    return config
  },
}
```

**Comment by thanksyouall** [comment] 2021-12-28 13:48
Can you fix this in your addon? Now I'm using the modified config from your webpack config and it works, but I wanna use addon-react-native-web.

**Comment by bouncycatt** [comment] 2021-12-28 13:49
Can you fix this? Now I'm using the modified config from your webpack config and it works, but I wanna use addon-react-native-web.

**Comment by dannyhw** [comment] 2021-12-28 16:33
> Can you fix this? Now I'm using the modified config from your webpack config and it works, but I wanna use addon-react-native-web.

@bouncycatt 

The reason you get this issue is probably because you are using process.env and it's being overwritten. The fix shouldn't be to remove the plugin but instead only add it if the process.env value is undefined.

Also I'm not able to fix it currently because I don't have a laptop right now and I'm away for the holidays. If you want to create a pr I'm happy to review it from my phone.

**Comment by bouncycatt** [comment] 2021-12-30 10:36
I don't quite understand how you want to fix the problem. So I'd rather wait for your change and be ready to test it.

**Comment by dannyhw** [comment] 2021-12-30 12:59
@bouncycatt ok no problem, I'll make the fix when I can.

**Comment by dannyhw** [comment] 2022-01-04 22:26
@bouncycatt im not really sure how to fix this because im not sure how to reproduce the problem. I added the linear gradient package in #31 without any issues.

Could you provide a public repo with a reproduction of the problem so that I can debug this issue?

**Comment by shilman** [comment] 2022-01-16 16:16
@bouncycatt that gist is slightly out of date -- I've updated that snippet now that CRA v5 has been released. which version are you on?

**Comment by bouncycatt** [comment] 2022-02-01 17:56
It turned out that our CRA uses Webpack 5, and Storybook uses Webpack 4. As a result, I put some packages to run Webpack 5, which are offered by storybook + updated storybook itself + added to main.ts "core: { builder: 'webpack5' }". Now the addon-react-native-web works correctly. 

Thank you all for your help!

**Comment by dannyhw** [comment] 2022-02-01 22:09
@bouncycatt that's great to hear, thanks for keeping us updated :). I'll close this for now then.

**Closed** 2022-02-01 22:10 UTC
Labels: bug
